# Generated by Django 3.1.5 on 2021-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_author_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_friendly',
            field=models.CharField(max_length=30),
        ),
    ]
