# Generated by Django 3.1.5 on 2021-02-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210207_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
