# Generated by Django 3.1.5 on 2021-02-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210207_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='story',
            new_name='article',
        ),
    ]
