# Generated by Django 3.1.5 on 2021-01-30 10:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toys', '0004_auto_20210119_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('procurement_date', models.DateTimeField(auto_now_add=True)),
                ('cart_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.toy')),
            ],
        ),
    ]
