# Generated by Django 3.1.5 on 2021-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210131_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
