# Generated by Django 3.1.5 on 2021-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210203_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
