# Generated by Django 3.1.5 on 2021-02-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toys', '0004_auto_20210119_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=500)),
                ('toy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='toys.toy')),
            ],
        ),
    ]
