# Generated by Django 3.1.5 on 2021-01-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name_plural': 'Age'},
        ),
        migrations.AlterModelOptions(
            name='toys',
            options={'verbose_name_plural': 'Toys'},
        ),
        migrations.AddField(
            model_name='toys',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
