# Generated by Django 3.1.5 on 2021-01-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20210117_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toys',
            new_name='Toy',
        ),
    ]
