# Generated by Django 3.1.5 on 2021-01-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_auto_20210117_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
