# Generated by Django 3.1.5 on 2021-02-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20210119_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
