# Generated by Django 3.1.5 on 2021-02-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_toyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='toyreview',
            name='toy_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toys.toy'),
        ),
    ]
