# Generated by Django 3.1.5 on 2021-02-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_auto_20210209_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toyreview',
            old_name='toy_review',
            new_name='toy_name',
        ),
    ]
