# Generated by Django 3.1.5 on 2021-02-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0008_auto_20210209_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toyreview',
            old_name='toy_name',
            new_name='toy',
        ),
    ]
