# Generated by Django 3.1.5 on 2021-02-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0009_auto_20210209_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toyreview',
            name='toy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='toys.toy'),
        ),
    ]
